version: '3.9'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ../mariadbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
    driver: local
